### ISSUE TITLE
uninitialized files are still initialized

### ISSUE THREAD

**Issue by milkev** [GlassPane/Mesh#6]
in my mod, more baked foods, i had a modid.mixins.json file. it was there purely because i forgot to delete it from my template mod. its not usually an issue, as i dont initialize it. it has incomplete arguments and attempts to load mixins that dont exist.

however... mesh is attempting to load it. a simple solution from my end is to delete the file, but its still odd that this mod is attempting to load some of my mods files, which my mod doesnt initialize at all, and arent even labeled correctly for my mod. perhaps mesh should do a simple check on that? or check if the file has errors in it before attempting to load it?

[https://github.com/milkev/More-Baked-Foods/issues/2](https://github.com/milkev/More-Baked-Foods/issues/2)

**Comment by UpcraftLP** [comment]
This error is not caused by Mesh, but rather by one of the other mods installed: it seems like some other mod didn't remove/rename the default `modid.mixins.json`, and because they have the same name/path, the mixin library cannot differentiate those files.

**Comment by milkev** [comment]
yes. that was my mod.
i dont initialize the file, and its only a leftover of my template mod. deleting it fixes the issue, but (as far as im aware) it is mesh that is attempting to load the file, which is clearly misnamed, and not initialized within my own mod.
my mod works fine on its own, but when mesh is installed, the game crashes

**Comment by UpcraftLP** [comment]
> yes. that was my mod.
> i dont initialize the file, and its only a leftover of my template mod. deleting it fixes the issue, but (as far as im aware) it is mesh that is attempting to load the file, which is clearly misnamed, and not initialized within my own mod.
> my mod works fine on its own, but when mesh is installed, the game crashes

Again, it is not caused by Mesh, but by some other mod that uses the same name for their mixins file.
The mixin library loaded your file instead, because it cannot differentiate them if they have the same name.

Mesh simply happened to load one of the affected classes.
