### ISSUE TITLE
Compatibility level set to JAVA_16

### ISSUE THREAD

**Issue by ClaudiusMinimus** [GlassPane/Mesh#7]
1.18-RC3 and RC4 server will not start with Compatibility level set to JAVA_16.
I was testing in my new mod pack, [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition) to run on a server and got this message. I narrowed it down to Mesh and then tried to run the server with only Mesh and the error persisted.

> Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))

	- fabricloader 0.12.5
	- java 17
	- mesh 0.18.0-alpha
	- mesh_api 0.18.0-alpha
	- minecraft 1.18-rc.3

[latest.log](https://github.com/GlassPane/Mesh/files/7620417/latest.log)

[console_log.txt](https://github.com/GlassPane/Mesh/files/7620423/console_log.txt)

**Comment by UpcraftLP** [comment]
alright, thanks for letting me know

**Comment by UpcraftLP** [comment]
alright, so apparently this is an issue with the current server installer (fixed in the next release of the installer+fabric loader).

I've set my mixin compatibility level to java 16 as a workaround.
